services:
  nep-exporter:
    image: ghcr.io/felix-engelmann/nationwideenergypartners-prometheus-exporter:main
    ports:
      - "8000:8000"                 # Prometheus will scrape this
    environment:
      # login to https://mynationwideenergypartners.com/
      USERNAME: "email"
      PASSWORD: "login"
    #env_file:
    #  - .env                        # reads USERNAME and PASSWORD from .env
    restart: unless-stopped